### ISSUE TITLE
Fail without information on issue

### ISSUE THREAD

**Issue by kalkairis** [hasadna/avid-covider-pipelines#11]
The preoprocess_raw_data fails in the pipeline and I don't understand from the Dashboard what is the issue.

**Comment by kalkairis** [comment]
@OriHoch

**Comment by OriHoch** [comment]
this is due to the tqdm library which is used for showing the geocoding multithreading progress

I added an option to disable it in Amirgav/COVID19-ISRAEL#258

now that it's merged I'll also enable it for the pipelines

**Comment by OriHoch** [comment]
ran without tqdm, still no info in logs, seems to just exit while geocoding

I suspect it might be related to the multithreading code, anyway not worth to investigate further now that I'm moving geocoding to our side
