### ISSUE TITLE
Remove stale files from cloud storage

### ISSUE THREAD

**Issue by kalkairis** [hasadna/avid-covider-pipelines#12]
Hi,

There are several stale files from the storage in `COVID19-ISRAEL`,
I only noticed them now when downloading using the PR I requested from you @OriHoch .

**Comment by OriHoch** [comment]
how can I know which are the stale files?

**Comment by kalkairis** [comment]
Inside COVID19-ISRAEL:
- 'data\dashboard_cache\*'
- 'data\New processed'
There might be others, but this should do.

**Comment by OriHoch** [comment]
done
