### ISSUE TITLE
Duplicated rows in daily CSV

### ISSUE THREAD

**Issue by akariv** [hasadna/avid-covider-pipelines#21]
e.g. 

<img width="679" alt="Screen Shot 2020-04-30 at 18 45 20" src="https://user-images.githubusercontent.com/265333/80731038-09023300-8b13-11ea-812e-fbc7214ac60a.png">

<img width="675" alt="Screen Shot 2020-04-30 at 18 45 25" src="https://user-images.githubusercontent.com/265333/80731035-08699c80-8b13-11ea-99a7-26f849fed827.png">

<img width="625" alt="Screen Shot 2020-04-30 at 18 45 43" src="https://user-images.githubusercontent.com/265333/80731032-069fd900-8b13-11ea-99a5-01bd44ae4eb2.png">

**Comment by OriHoch** [comment]
opened an issue on Trello
