### ISSUE TITLE
Adapt corona_data_collector to avid-covider data version 2.7.x

### ISSUE THREAD

**Issue by akariv** [hasadna/avid-covider-pipelines#7]
One field was removed in this version.

@OriHoch who should approve from WIS side?

**Comment by OriHoch** [comment]
the field that was removed is `symptoms_sore_throat`

I don't know who should approve this

Need to also know if the column should be removed from the output csvs, set to an empty string or something else?

**Comment by OriHoch** [comment]
@kalkairis

**Comment by kalkairis** [comment]
Why did you remove sore throat?

**Comment by akariv** [comment]
My mistake - it wasn't removed.
This symptom appeared in two locations in the questionnaire, now it appears
only once but it is still being sent.

**Comment by OriHoch** [comment]
cool, so to clarify - there is no change in the data between 2.7.1 and 2.6.0 ?
@akariv

**Comment by akariv** [comment]
yes

**Comment by OriHoch** [comment]
done in #10
